### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mbpz** [XuDaojie/QRCode-Android#10]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=460800 srcPos=-19140 dst.length=172800 dstPos=0 length=360
       at java.lang.System.arraycopy(System.java)
       at io.github.xudaojie.qrcodelib.zxing.camera.PlanarYUVLuminanceSource.getMatrix(PlanarYUVLuminanceSource.java:96)
       at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:70)
       at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
       at io.github.xudaojie.qrcodelib.zxing.decoding.DecodeHandler.decode(DecodeHandler.java:88)
       at io.github.xudaojie.qrcodelib.zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:57)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at io.github.xudaojie.qrcodelib.zxing.decoding.DecodeThread.run(DecodeThread.java:81)

**Comment by chenyun122** [comment]
I got this error at the same place too.
