### ISSUE TITLE
选择相册里面的二维码会闪退

### ISSUE THREAD

**Issue by lodgkk** [XuDaojie/QRCode-Android#4]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { dat=file:///storage/emulated/0/DCIM/Camera/IMG_20161101_160716.jpg typ=image/jpeg }} to activity {com.xfkj.schoolcar/com.xfkj.schoolcar.view.qrcode.SimpleCaptureActivity}: java.lang.NullPointerException
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3357)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3400)
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1250)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5047)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.NullPointerException
                                                                        at io.github.xudaojie.qrcodelib.CaptureActivity.onActivityResult(CaptureActivity.java:151)
                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:5441)
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3353)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3400) 
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1250) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5047) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by XuDaojie** [comment]
你是相册里所有的图片都报错还是部分图片报错

**Comment by lodgkk** [comment]
我刚刚又测试了一次,我是小米3,有时候选的图片会报错,就是我上传的那个空指针异常,应该是游标为空,有时候又不会报错,会弹提示框说该图片无法识别

**Comment by XuDaojie** [comment]
已经改过了，你可以试下v0.4.1
这个问题是因为其他的系统相册返回的contentUri，而小米是直接返回的fileUri

**Comment by lodgkk** [comment]
已经修复了,但是有个问题,就是在restartPreview();这个方法之前,先判断一下getHandler()是否为空个,不然也会报空指针异常

**Comment by XuDaojie** [comment]
好的 谢谢提醒.

**Comment by jinmei339** [comment]
部分相册中的图片在识别时会弹提示框说该图片无法识别

**Comment by XuDaojie** [comment]
图片必须是本地的，如果是备份在云上的就无法识别。 @jinmei339
